services:
  app:
    image: tangzh2021/stress-backend:latest
    build:
      context: .
      dockerfile: dockerfile.app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:14.12
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: